"""
Setup wizard — interactive onboarding for first-time configuration.
Guides the user through: LLM API key, CRM provider, and gateway selection.
"""

from __future__ import annotations

import os
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

console = Console()


async def run_setup_wizard() -> None:
    """Interactive setup wizard."""
    console.print(
        Panel(
            "[bold cyan]SalesPossible Setup Wizard[/bold cyan]\n"
            "Configure your API keys, CRM, and messaging gateways.",
            border_style="cyan",
        )
    )

    env_path = Path(".env")
    existing: dict[str, str] = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                existing[k.strip()] = v.strip()

    lines: list[str] = ["# SalesPossible .env — generated by setup wizard\n"]

    # ── LLM ──────────────────────────────────────────────────────────────────
    console.print("\n[bold]Step 1: LLM API Key[/bold]")
    console.print("Get your key from: https://console.anthropic.com/")
    current_key = existing.get("ANTHROPIC_API_KEY", "")
    hint = f" [dim](current: {current_key[:12]}...)[/dim]" if current_key else ""
    api_key = Prompt.ask(f"Anthropic API key{hint}", default=current_key or "", password=True)
    if api_key:
        lines.append(f"ANTHROPIC_API_KEY={api_key}")

    # ── CRM ───────────────────────────────────────────────────────────────────
    console.print("\n[bold]Step 2: CRM Integration[/bold]")
    crm_choice = Prompt.ask(
        "CRM provider",
        choices=["mock", "hubspot", "salesforce"],
        default="mock",
    )
    lines.append(f"CRM_PROVIDER={crm_choice}")

    if crm_choice == "hubspot":
        hs_key = Prompt.ask("HubSpot API key", password=True)
        lines.append(f"HUBSPOT_API_KEY={hs_key}")

    # ── Gateways ──────────────────────────────────────────────────────────────
    console.print("\n[bold]Step 3: Messaging Gateways[/bold]")

    if Confirm.ask("Enable Telegram gateway?", default=False):
        tg_token = Prompt.ask("Telegram bot token (from @BotFather)", password=True)
        lines.append(f"TELEGRAM_BOT_TOKEN={tg_token}")

    # ── Email ─────────────────────────────────────────────────────────────────
    console.print("\n[bold]Step 4: Email (optional)[/bold]")
    if Confirm.ask("Configure SMTP for sending emails?", default=False):
        smtp_host = Prompt.ask("SMTP host", default="smtp.gmail.com")
        smtp_port = Prompt.ask("SMTP port", default="587")
        smtp_user = Prompt.ask("SMTP username / email")
        smtp_pass = Prompt.ask("SMTP password / app password", password=True)
        lines.extend([
            f"SMTP_HOST={smtp_host}",
            f"SMTP_PORT={smtp_port}",
            f"SMTP_USERNAME={smtp_user}",
            f"SMTP_PASSWORD={smtp_pass}",
            f"SMTP_FROM={smtp_user}",
        ])

    # ── Write .env ────────────────────────────────────────────────────────────
    env_path.write_text("\n".join(lines) + "\n")

    console.print(
        Panel(
            "[green]Setup complete![/green] .env written.\n\n"
            "Start the agent with:\n"
            "  [bold]salespossible[/bold]          — CLI interface\n"
            "  [bold]salespossible --gateway telegram[/bold]  — Telegram bot",
            border_style="green",
        )
    )
